networks:
  ai_bridge_network:
    external: true 
    
services:
  deepstream:
    container_name: deepstream
    image: nvcr.io/nvidia/deepstream:7.0-triton-multiarch
    gpus: all
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - /run/user/1000:/run/user/1000
      - ./:/workspace/FallDetection
    networks:
      - ai_bridge_network
    ipc: host
    command: tail -f /dev/null